##################
### WINDOW RULE###
##################

# Float
windowrulev2 = float, class:^(org.gnome.Calculator)$
windowrulev2 = float, class:^(org.kde.gwenview)(.*)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(org.fcitx.fcitx5-config-qt)$
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(OpenTabletDriver.UX)$


# Dialogues
windowrulev2 = float, title:^(.*)(Properties)$
windowrulev2 = float, title:^(Open)(.*)$
windowrulev2 = float, title:^(Select)(.*)$
windowrulev2 = float, title:^(Choose)(.*)$
windowrulev2 = float, title:^(Save)(.*)$
windowrulev2 = float, title:^(.*)(Upload)(.*)$

windowrulev2 = center, title:^(.*)(Properties)$
windowrulev2 = center, title:^(Open(.*)$
windowrulev2 = center, title:^(Select)(.*)$
windowrulev2 = center, title:^(Choose)(.*)$
windowrulev2 = center, title:^(Save)(.*)$
windowrulev2 = center, title:^(.*)(Upload)(.*)$

# Video playback & PIP support
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = opaque, on, title:^(Picture-in-Picture)$
windowrulev2 = opaque, on, title:^(.*)(YouTube)(.*)$
windowrulev2 = opaque, on, class:^(vlc)$

# Game support
windowrulev2 = center, title:^(Lutris settings)$
windowrulev2 = center, title:^(Add a new game)$

windowrulev2 = fullscreen, on, class:^(steam_app_727)$
windowrulev2 = allowsinput, on, class:^(steam_app_727)$
windowrulev2 = fullscreen, on, initialTitle:^(.*)(Stray)(.*)$
windowrulev2 = fullscreen, on, initialTitle:^(.*)(DARK SOULS)(.*)$
windowrulev2 = idleinhibit focus,  initialTitle:^(.*)(DARK SOULS)(.*)$
windowrulev2 = idleinhibit focus,  initialTitle:^(.*)(Stray)(.*)$
windowrulev2 = idleinhibit focus,  class:^(steam_app_727)$

# VM support
windowrulev2 = fullscreen, on, class:^(looking-glass-client)$

# Ignore maximize command
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Check if window is XWayland
windowrulev2 = bordercolor rgb(ff5555),xwayland:1
